const movies = [
    {
        title: 'Love and Monsters',
        img: 'assets/movie1.jpg',
        trailer: 'https://www.youtube.com/embed/YZhI4aHAgP0',
        dateTime: '26-01-2021 | 13:00 - 14:00 [1h 49m]',
        synopsis: 'Seven years after the Monsterpocalypse, Joel Dawson, along with the rest of humanity, has been living underground ever since giant creatures took control of the land. After reconnecting over the radio with his high school girlfriend, Aimee, who is now 80 miles away at a coastal colony, Joel begins to fall for her again. As Joel realizes that there\'s nothing left for him underground, he decides to venture out to Aimee, despite all the dangerous monsters that stand in his way.',
        genre: 'Action, Comedy, Adventure',
        duration: '1h 49m',
        director: 'Michael Matthews',
        producers: 'Shawn Levy, Dan Cohen',
        screenplay: 'Brian Duffield, Matthew Robinson',
        cast: 'Dylan O\'Brien, Jessica Henwick, Michael Rooker, Ariana Greenblatt, Ellen Hollman'
    },  
    {
        title: 'Tenet',
        img: 'assets/movie2.jpg',
        trailer: 'https://www.youtube.com/embed/L3pk_TBkihU',
        dateTime: '26-01-2021 | 19:30 - 22:10 [2h 30m]',
        synopsis: 'A secret agent embarks on a dangerous, time-bending mission to prevent the start of World War III.',
        genre: 'Sci Fi, Action, Mystery, Thriller',
        duration: '2h 30m',
        director: 'Christoper Nolan',
        producers: 'Emma Thomas, Christopher Nolan',
        screenplay: 'Christoper Nolan',
        cast: 'Elizabeth Debicki, Robert Pattinson, John David Washington, Kenneth Branagh'
    },
    {
        title: 'Unhinged',
        img: 'assets/movie3.jpg',
        trailer: 'https://www.youtube.com/embed/vdxDXoODKN8',
        dateTime: '28-01-2021 | 15:45 - 17:25 [1h 30m]',
        synopsis: 'Rachel is a single mother whose bad day gets even worse when she beeps her horn at a fellow driver during rush-hour traffic. After an exchange of words, she soon realizes that the mysterious man is following her and her young son in his truck. The initial case of road rage quickly escalates into full-blown terror as Rachel discovers the psychopath\'s sinister plan for revenge.',
        genre: 'Mystery, Thriller',
        duration: '1h 30m',
        director: 'Derrick Borte',
        producers: 'Lisa Ellzey, Andrew Gunn, Mark Gill',
        screenplay: 'Carl Ellsworth',
        cast: 'Russel Crowe, Caren Pistorius, Gabriel Bateman, Jimmi Simpson'
    },
    {
        title: 'Monster Hunter',
        img: 'assets/movie4.jpg',
        trailer: 'https://www.youtube.com/embed/3od-kQMTZ9M',
        dateTime: '28-01-2021 | 20:00 - 22:00 [1h 43m]',
        synopsis: 'Behind our world, there is another -- a world of dangerous and powerful monsters that rule their domain with deadly ferocity. When Lt. Artemis and her loyal soldiers are transported from our world to the new one, the unflappable lieutenant receives the shock of her life. In a desperate battle for survival against enormous enemies with incredible powers and unstoppable, terrifying attacks, Artemis teams up with a mysterious hunter who has found a way to fight back.',
        genre: 'Adventure, Action, Fantasy',
        duration: '1h 43m',
        director: 'Paul W. S. Anderson',
        producers: 'Jeremy Bolt, Paul W. S. Anderson, Dennis Berardi, Robert Kulzer, Martin Moszkowicz',
        screenplay: 'Paul W. S. Anderson',
        cast: 'Milla Jovovich, Ron Perlman, Tony Jaa, Diego Boneta'
    },
    {
        title: 'Honest Thief',
        img: 'assets/movie5.jpg',
        trailer: 'https://www.youtube.com/embed/ZUIEOMOxIDo',
        dateTime: '30-01-2021 | 21:00 - 23:00 [1h 39m]',
        synopsis: 'Hoping to cut a deal, a professional bank robber agrees to return all the money he stole in exchange for a reduced sentence. But when two FBI agents set him up for murder, he must now go on the run to clear his name and bring them to justice.',
        genre: 'Mystery, Thriller, Action',
        duration: '1h 39m',
        director: 'Mark Williams',
        producers: 'Mark Williams, Myles Nestel, Tai Duncan, Craig Chapman',
        screenplay: 'Mark Williams, Steve Allrich',
        cast: 'Liam Neeson, Kate Walsh, Robert Patrick, Anthony Ramos'
    },
    {
        title: 'Raya and the Last Dragon',
        img: 'assets/movie6.jpg',
        trailer: 'https://www.youtube.com/embed/9BPMTr-NS9s',
        synopsis: 'Long ago, in the fantasy world of Kumandra, humans and dragons lived together in harmony. However, when sinister monsters known as the Druun threatened the land, the dragons sacrificed themselves to save humanity. Now, 500 years later, those same monsters have returned, and it\'s up to a lone warrior to track down the last dragon and stop the Druun for good.',
        genre: 'Fantasy, Adventure, Kids And Family, Animation',
        duration: 'N/A',
        director: 'Don Hall, Carlos López Estrada',
        producers: 'Osnat Shurer, Peter Del Vecho',
        screenplay: 'Adele Lim, Qui Nguyen',
        cast: 'Kelly Marie Tran, Awkwafina'
    },
    {
        title: 'Dune',
        img: 'assets/movie7.jpg',
        trailer: 'https://www.youtube.com/embed/n9xhJrPXop4',
        synopsis: 'Paul Atreides leads nomadic tribes in a battle to control the desert planet Arrakis.',
        genre: 'Adventure, Sci Fi',
        duration: 'N/A',
        director: 'Denis Villeneuve',
        producers: 'Cale Boyter, Joe Caracciolo Jr., Mary Parent, Denis Villeneuve',
        screenplay: 'Jon Spaihts, Denis Villeneuve, Eric Roth',
        cast: 'Timothée Chalamet, Josh Brolin, Jason Momoa, Oscar Isaac, Javier Bardem, Zendaya'
    },
    {
        title: 'Black Widow',
        img: 'assets/movie8.jpg',
        trailer: 'https://www.youtube.com/embed/ybji16u608U',
        synopsis: 'International spy and assassin Natasha Romanoff becomes the superhero Black Widow.',
        genre: 'Adventure, Action',
        duration: 'N/A',
        director: 'Cate Shortland',
        producers: 'Kevin Feige',
        screenplay: 'Eric Pearson, Jac Schaeffer, Ned Benson',
        cast: 'Scarlett Johansson, Florence Pugh, David Harbour, Rachel Weisz, Robert Downey Jr., Ray Winstone'
    },
    {
        title: 'The Suicide Squad',
        img: 'assets/movie9.jpg',
        trailer: 'https://www.youtube.com/embed/4stoUyTYbmc',
        synopsis: 'The further adventures of Harley Quinn, Rick Flag and their team of assembled supervillains.',
        genre: 'Adventure, Comedy, Action',
        duration: 'N/A',
        director: 'James Gunn',
        producers: 'Charles Roven, Peter Safran',
        screenplay: 'David Ayer',
        cast: 'Margot Robbie, Idris Elba, Sylvester Stallone, John Cena, Joel Kinnaman, Viola Davis'
    },
    {
        title: 'No Time to Die',
        img: 'assets/movie10.jpg',
        trailer: 'https://www.youtube.com/embed/vw2FOYjCz38',
        synopsis: 'Recruited to rescue a kidnapped scientist, globe-trotting spy James Bond finds himself hot on the trail of a mysterious villain who\'s armed with a dangerous new technology.',
        genre: 'Adventure, Mystery, Thriller, Action',
        duration: 'N/A',
        director: 'Cary Joji Fukunaga',
        producers: 'Barbara Broccoli, Michael G. Wilson',
        screenplay: 'Jon Spaihts, Denis Villeneuve, Eric Roth',
        cast: 'Daniel Craig, Rami Malek, Ralph Fiennes, Naomie Harris, Léa Seydoux, Rory Kinnear'
    },
]
